import test from "node:test";
import assert from "node:assert/strict";
import { pool } from "@workspace/db";
import { CreateTeamBody } from "@workspace/api-zod";
import profileRouter from "../routes/moon-profile";
import { teamMapLeaderboard } from "./team-leaderboard";

const input={userId:1,name:"Fixture",routeId:1,today:"2026-01-01",endDate:"2099-12-31"};
test("leaderboard create validation: omitted, false, true; no coercion",()=>{
  assert.equal(CreateTeamBody.parse(input).leaderboardEnabled,false);
  for(const value of [false,true]) assert.equal(CreateTeamBody.parse({...input,leaderboardEnabled:value}).leaderboardEnabled,value);
  for(const value of [null,0,1,"false","true",{},[]]) assert.equal(CreateTeamBody.safeParse({...input,leaderboardEnabled:value}).success,false);
});

// Explicit opt-in for development only. Temporary tables shadow every table
// touched by these tests: no application rows or sequences are ever mutated.
test("creation persistence, legacy default, authorization, exact map attribution and stable ties",
  {skip:process.env.RUN_LEADERBOARD_DB_TESTS!=="development"},async()=>{
  const c=await pool.connect(),originalQuery=pool.query,originalConnect=pool.connect;
  await c.query("BEGIN");
  try {
    for(const table of ["moon_users","moon_routes","moon_teams","moon_members","moon_maps","moon_runs"]) {
      await c.query(`CREATE TEMP TABLE ${table} (LIKE public.${table} INCLUDING DEFAULTS) ON COMMIT DROP`);
      // Replace serial defaults with private test identities, not public sequences.
      await c.query(`ALTER TABLE ${table} ALTER COLUMN id DROP DEFAULT`);
      await c.query(`ALTER TABLE ${table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY`);
    }
    pool.query=c.query.bind(c) as typeof pool.query;
    pool.connect=(async()=>({
      query:(sql:string,args?:unknown[])=>["BEGIN","COMMIT","ROLLBACK"].includes(sql)?Promise.resolve({rows:[],rowCount:0}):c.query(sql,args),
      release:()=>{},
    })) as typeof pool.connect;
    const invoke=async(path:string,method:string,body:unknown,query:unknown={})=>{
      const layer=(profileRouter as any).stack.find((l:any)=>l.route?.path===path&&l.route.methods[method]);
      let status=200,result:any;
      const res={status:(s:number)=>{status=s;return res;},json:(v:unknown)=>{result=v;return res;}};
      await layer.route.stack[0].handle({body,query,log:{error:()=>{}}},res);
      return {status,result};
    };
    await c.query("INSERT INTO moon_users(name,avatar_emoji) VALUES ('A','🌙'),('B','🌙'),('Zero','🌙'),('Outsider','🌙')");
    await c.query("INSERT INTO moon_routes(name,type,total_miles,emoji,gradient_from,gradient_to) VALUES ('One','journey',100,'🌙','#000','#fff'),('Two','journey',100,'🌙','#000','#fff')");
    const teams=[];
    for(const value of [undefined,false,true]) {
      const body={...input,...(value===undefined?{}:{leaderboardEnabled:value})};
      const created=await invoke("/moon/teams","post",body);
      assert.equal(created.status,201);
      assert.equal(created.result.leaderboardEnabled,value??false);
      const stored=(await c.query("SELECT leaderboard_enabled FROM moon_teams WHERE id=$1",[created.result.id])).rows[0];
      assert.equal(stored.leaderboard_enabled,value??false);
      teams.push(created.result.id);
    }
    const legacy=(await c.query("INSERT INTO moon_teams(name,invite_code,owner_user_id,route_id,end_date) VALUES ('Old','OLD123',1,1,'2099-12-31') RETURNING leaderboard_enabled")).rows[0];
    assert.equal(legacy.leaderboard_enabled,false);
    const team=teams[2],otherTeam=teams[1];
    await c.query("INSERT INTO moon_members(team_id,user_id) VALUES($1,2),($1,3)",[team]);
    const map=(await c.query("SELECT id FROM moon_maps WHERE team_id=$1",[team])).rows[0].id;
    const otherMap=(await c.query("INSERT INTO moon_maps(team_id,route_id,end_date) VALUES($1,2,'2099-12-31') RETURNING id",[team])).rows[0].id;
    const solo=(await c.query("INSERT INTO moon_maps(solo_user_id,route_id,end_date) VALUES(1,1,'2099-12-31') RETURNING id")).rows[0].id;
    const disabledMap=(await c.query("SELECT id FROM moon_maps WHERE team_id=$1",[otherTeam])).rows[0].id;
    assert.deepEqual((await teamMapLeaderboard(team,map,1)).members.map(m=>m.miles),[0,0,0]);
    const run=async(user:number,t:number|null,m:number|null,miles:number,day="2026-01-01")=>
      c.query("INSERT INTO moon_runs(user_id,team_id,map_id,route_id,miles,duration_minutes,logged_at,request_id) VALUES($1,$2,$3,1,$4,10,$5,$6)",[user,t,m,miles,day,`fixture-${user}-${t}-${m}-${day}`]);
    await run(1,team,map,2,"2000-01-01");
    await run(2,team,map,2,"2099-01-01");
    await run(1,team,otherMap,10);
    await run(1,null,solo,20);
    await run(1,otherTeam,disabledMap,30);
    await run(1,team,null,40);
    // Even inconsistent legacy rows cannot leak solo/other-team contributions.
    await run(1,null,map,50);
    await run(1,otherTeam,map,60);
    const first=await teamMapLeaderboard(team,map,1);
    assert.deepEqual(first.members.map(m=>[m.userId,m.miles,m.rank]),[[1,2,1],[2,2,2],[3,0,3]]);
    assert.deepEqual(await teamMapLeaderboard(team,map,2),first);
    assert.equal((await teamMapLeaderboard(team,otherMap,1)).members[0].miles,10);
    assert.deepEqual((await teamMapLeaderboard(otherTeam,disabledMap,1)).members,[]);
    await assert.rejects(teamMapLeaderboard(team,map,4),{status:403});
    await assert.rejects(teamMapLeaderboard(otherTeam,disabledMap,4),{status:403});
    await assert.rejects(teamMapLeaderboard(team,solo,1),{status:404});
    await assert.rejects(teamMapLeaderboard(team,disabledMap,1),{status:404});
    await assert.rejects(teamMapLeaderboard(team,2147483647,1),{status:404});
    await assert.rejects(teamMapLeaderboard(team,map,NaN),{status:400});
    await run(2,team,map,1,"2026-01-02");
    assert.deepEqual((await teamMapLeaderboard(team,map,1)).members.map(m=>[m.userId,m.miles]),[[2,3],[1,2],[3,0]]);
    await c.query("DELETE FROM moon_members WHERE team_id=$1 AND user_id=2",[team]);
    await assert.rejects(teamMapLeaderboard(team,map,2),{status:403});
    assert.deepEqual((await teamMapLeaderboard(team,map,1)).members.map(m=>m.userId),[1,3]);
  } finally {
    pool.query=originalQuery;pool.connect=originalConnect;
    await c.query("ROLLBACK");c.release();await pool.end();
  }
});